name: CI Tests

on:
  push:
  pull_request:

jobs:
  test-ci:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./node

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn test
        env:
          CI: true
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}
          NODE_ENV: ${{ secrets.NODE_ENV }}

  test-docker-compose:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:app appropriate/curl -s --retry 10 --retry-connrefused http://app:3000/
  dev-task:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Build the stack
        run: docker-compose up --build -d
      - name: Test
        run: docker run --network container:app appropriate/curl -s --retry 10 --retry-connrefused http://app:3000/
